top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/test
builddir     = /home/auser/httpd-2.4.7/modules/test
VPATH        = /home/auser/httpd-2.4.7/modules/test
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
