top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/mappers
builddir     = /home/auser/httpd-2.4.7/modules/mappers
VPATH        = /home/auser/httpd-2.4.7/modules/mappers

include $(top_srcdir)/build/special.mk

