top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules
builddir     = /home/auser/httpd-2.4.7/modules
VPATH        = /home/auser/httpd-2.4.7/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

