top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/echo
builddir     = /home/auser/httpd-2.4.7/modules/echo
VPATH        = /home/auser/httpd-2.4.7/modules/echo

include $(top_srcdir)/build/special.mk

