top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/filters
builddir     = /home/auser/httpd-2.4.7/modules/filters
VPATH        = /home/auser/httpd-2.4.7/modules/filters

include $(top_srcdir)/build/special.mk

