top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/server/mpm/event
builddir     = /home/auser/httpd-2.4.7/server/mpm/event
VPATH        = /home/auser/httpd-2.4.7/server/mpm/event
include $(top_srcdir)/build/special.mk
