top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/cache
builddir     = /home/auser/httpd-2.4.7/modules/cache
VPATH        = /home/auser/httpd-2.4.7/modules/cache

include $(top_srcdir)/build/special.mk

