top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/modules/core
builddir     = /home/auser/httpd-2.4.7/modules/core
VPATH        = /home/auser/httpd-2.4.7/modules/core

include $(top_srcdir)/build/special.mk

