top_srcdir   = /home/auser/httpd-2.4.7
top_builddir = /home/auser/httpd-2.4.7
srcdir       = /home/auser/httpd-2.4.7/server/mpm
builddir     = /home/auser/httpd-2.4.7/server/mpm
VPATH        = /home/auser/httpd-2.4.7/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
